-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 15:37:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Estado` (
  `id_Estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Estado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Habitacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habitacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Habitacion` (
  `id_Habitacion` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `fk_Estado` INT NOT NULL,
  PRIMARY KEY (`id_Habitacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Metodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Metodo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Metodo` (
  `id_Metodo` INT NOT NULL AUTO_INCREMENT,
  `metodo_pago` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_Metodo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagos` (
  `id_Pagos` INT NOT NULL AUTO_INCREMENT,
  `pago_total` DOUBLE NOT NULL,
  `fk_Metodo` INT NOT NULL,
  `fk_Reserva` INT NOT NULL,
  PRIMARY KEY (`id_Pagos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reservas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Reservas` (
  `id_Reserva` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `fk_Usuario` INT NOT NULL,
  `fk_Habitacion` INT NOT NULL,
  PRIMARY KEY (`id_Reserva`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Rol` (
  `id_Rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `telefono` INT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `fk_Rol` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `Usuario` (`email` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
